### ISSUE TITLE
Release Beta version of Airship

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#398]
Upgrade Airship to beta status and ship it.

- [x] Update CHANGELOG
- [x] Adapt README
- [x] Update version
- [x] Publish to NPM
- [x] Publish to CDN
- [x] Change Airship minisite link to documentation
- [x] Profit

**Comment by ivanmalagon** [comment]
🚀
