### ISSUE TITLE
Elements CSS

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#43]
We have to implement the basic elements of the Airship framework. Please use as reference https://projects.invisionapp.com/share/3REYL6RJK

These elements will be built using only CSS. For most complex elements we'll create Custom Elements.

If you find that any them that can't be built only with CSS, please give the team a heads up.

Basic CSS
- [x] Colors #75
- [x] Typography #76
  - [x] Jumbo
  - [x] Display
  - [x] Title (normal / bold)
  - [x] Subheader (normal / bold / mono)
  - [x] Body (normal / bold / mono)
  - [x] Caption (normal / bold / mono)
- [x] List #76
  - [x] Bulleted
  - [x] Numbered
- [x] Icons #77

Elements
- [x] Buttons
- [x] Inputs, textarea
- [x] Checkbox
- [x] Radio buttons
- [x] Tabs (WC?)
- [x] Banner
- [x] Flags
- [x] Avatar
- [x] Tooltips
- [x] Breadcrumbs
- [x] Menu dropdown (perhaps we can reuse dropdown style. Create a WC as well?)
- [x] Badges
- [x] Switch (should we create a WC also?)
- [x] Loading (global, block, title)

Nice to have
- [x] Table
