### ISSUE TITLE
Smoke tests

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#489]
### CHROME

In responsive:
- [x] First tab. Tabs not clickable. #490
- [x] First tab. Switch not clickable. #490
- [x] Widget tabs. Widgets rendered wrongly. Super extra small.
- [x] Lots of `Error: <rect> attribute width: A negative value is not valid.` errors.

### FIREFOX

- [x] Histogram `clear selection` does not work.
- [x] Histogram doesn't suit to its container.

### SAFARI
- [x] Histogram doesn't suit to its container.

### IE11
- [x] Right sidebar not showing #491
- [x] Left sidebar is on top of the map area. #491

**Comment by IagoLast** [comment]
> Widget tabs. Widgets rendered wrongly. Super extra small.

I think that's because you need to populate the widgets when the `as-responsive-content` is ready. ( Read the docs :trollface: )

**Comment by ivanmalagon** [comment]
![facepalm](https://user-images.githubusercontent.com/1078228/48480287-27cf1580-e80a-11e8-94a3-7625a5250c1d.gif)

That's the kind of issues I like. The ones we know already the fix. :)

**Comment by AbelVM** [comment]
Some suggestions:
* https://github.com/CartoDB/airship/issues/430
* https://github.com/CartoDB/airship/issues/471

:grin:

**Comment by IagoLast** [comment]
fixed this week
